server:
  port: 8888
spring:
  application:
    name: config-service
  rabbitmq:
    host: 54.180.140.136
    port: 5672
    username: guest
    password: guest
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///C:\Users\ghkd3\work\git\e-commerce\config

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh