server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone : http://localhost:8761/eureka

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      mvc:
        routes:
          - id: user-service
            uri : lb://USER-SERVICE
            predicates:
              - Path=/user-service/**
          - id: item-service
            uri: lb://ITEM-SERVICE
            predicates:
              - Path=/item-service/**
          - id: order-service
            uri: lb://ORDER-SERVICE
            predicates:
              - Path=/order-service/**
          - id: review-service
            uri: lb://REVIEW-SERVICE
            predicates:
              - Path=/review-service/**
          - id: image-service
            uri: lb://IMAGE-SERVICE
            predicates:
              - Path=/image-service/**



token:
  key: secret
