server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone : http://localhost:8761/eureka

spring:
  application:
    name: apigateway-service
  rabbitmq:
    host: 54.180.140.136
    port: 5672
    username: guest
    password: guest
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/login, /user-service/register
        - id: user-service
          uri : lb://USER-SERVICE
          predicates:
            - Path=/user-service/**
          filters:
            - name: AuthFilter
        - id: item-service
          uri: lb://ITEM-SERVICE
          predicates:
            - Path=/item-service/add
          filters:
            - AuthFilter
        - id: item-service
          uri: lb://ITEM-SERVICE
          predicates:
            - Path=/item-service/**
            - Method=DELETE
          filters:
            - AuthFilter
        - id: item-service
          uri: lb://ITEM-SERVICE
          predicates:
            - Path=/item-service/update/**
            - Method=PATCH
          filters:
            - AuthFilter
        - id: item-service
          uri: lb://ITEM-SERVICE
          predicates:
            - Path=/item-service/**
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order-service/**
          filters:
            - name: AuthFilter
        - id: review-service
          uri: lb://REVIEW-SERVICE
          predicates:
            - Path=/review-service/write/**, /review-service/update/**
          filters:
            - name: AuthFilter
        - id: review-service
          uri: lb://REVIEW-SERVICE
          predicates:
            - Path=/review-service/**
        - id: image-service
          uri: lb://IMAGE-SERVICE
          predicates:
            - Path=/image-service/upload
          filters:
            - name: AuthFilter
        - id: image-service
          uri: lb://IMAGE-SERVICE
          predicates:
            - Path=/image-service/update/**
          filters:
            - name: AuthFilter
        - id: image-service
          uri: lb://IMAGE-SERVICE
          predicates:
            - Path=/image-service/**
        - id: pay-service
          uri: lb://PAY-SERVICE
          predicates:
            - Path=/pay-service/**

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh





token:
  key: "c7L0+z1bI67OpGIeYN9NcKgXBsHKiR2RlYX1Vzj4ULA="
